CNComicBundle:
    resource: "@CNComicBundle/Resources/config/routing.yml"
    prefix:   /

CodeNotionComicBundle:
    resource: "@CodeNotionComicBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
